#!/bin/bash

[ $(id -u) = 0 ] || { echo "error: going to need root" >&2; exit 1; }

if [ ! -f letsgo.img ]; then
    qemu-img create -f qcow2 letsgo.img 16G
fi

exec qemu-system-x86_64 \
    -cdrom iso/archlinux-2021.06.01-x86_64.iso \
    -boot once=d \
    -drive file=letsgo.img \
    -m 4G \
    -enable-kvm \
    -cpu host \
    -smp 4 \
    -bios /usr/share/edk2-ovmf/x64/OVMF.fd
